server:
  port: 8081
spring:
  application:
    name: app-item
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka
    register-with-eureka: true
    fetch-registry: true
